version: '3.9'
services:
  products:
    image: "${DOCKER_LOCAL_IMAGE}"
    ports:
      - 3445:3445
    depends_on:
      - dynamodb
    command: "node src/server.js"
    restart: on-failure

  dynamodb:
    image: amazon/dynamodb-local:1.18.0
    ports:
      - 8000:8000
    volumes:
      - ./dynamodb_data:/home/dynamodblocal/data
    restart: always