{{- if .Release.IsInstall }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "products.secrets" . }}
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  accessKeyId: {{ .Values.dynamodb.accessKeyId }}
  secretAccessKey: {{ .Values.dynamodb.secretAccessKey }}
{{- end }}
